name: "\U0001F4DA Documentation Update"
description: Request an update to the GULPS documentation
title: "[Documentation]: "
labels: ["documentation"]
assignees:
  - evmckinney9
body:
  - type: textarea
    id: documentation-section
    attributes:
      label: Documentation Section
      placeholder: Link to the page or section.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      placeholder: Describe what is incorrect or missing.
    validations:
      required: true
  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      placeholder: Describe the proposed change.
    validations:
      required: false
